### PR TITLE
Test hidden modeless dialog

### PR DESCRIPTION
**Pull request by ppescher**
Address save/restore on a modeless dialog initially hidden, that was incorrectly making it visible during initialization.

Now the restore process is postponed until the dialog is made visible for the first time, preventing the override of the initial hidden state.

See pull request #32 for details. Anyone interested please try this patch also in your own use cases, to confirm it does what it's supposed to and there are no unexpected side-effects.

### CODE REVIEW

**Comment by irwir** [comment]
_Moved this comment to the correct PR._
The changes so far look good; dialogs with visible initial state behaved as usual.

**Comment by adipose** [comment]
This fixes the issue for mpc-hc after removal of our custom code.

**Comment by ppescher** [comment]
Nice! I will propagate this change to the other dialog flavors.

**Comment by adipose** [comment]
Any chance of this making it to master soon?

I have updated mpc-hc code to take advantage but I would like it to be based on commited code.

**Comment by adipose** [comment]
@ppescher will this make it to the main branch?

**Comment by ppescher** [comment]
Sorry, I've been completely carried away from this. Merged.

**Pull request merged**
